apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-03-24T13:03:48.795924677-04:00"
    description: A Helm chart for the Deployment Manager
    digest: 71fae84d7f472bfeb291c2acfe856212ac397df9680a90cca5e39a705db5f5ec
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-2.0.10.tgz
    version: 2.0.10
generated: "2023-03-24T13:03:48.792998285-04:00"
