apiVersion: starlingx.windriver.com/v1
kind: HostProfile
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: controller-profile
  namespace: deployment
spec:
<<<<<<< HEAD
  hwSettle: "0"
=======
  hwSettle: "0"

>>>>>>> 57edebc3c8608fba3260997c8dc8f4739e8e1c68
